In [12]:
import numpy as np
import pandas as pd

In [13]:
df=pd.read_csv("/content/IMDB Dataset.csv")

In [14]:
df

                                                  review sentiment
0      One of the other reviewers has mentioned that ...  positive
1      A wonderful little production. <br /><br />The...  positive
2      I thought this was a wonderful way to spend ti...  positive
3      Basically there's a family where a little boy ...  negative
4      Petter Mattei's "Love in the Time of Money" is...  positive
...                                                  ...       ...
50776  I thought this movie did a down right good job...  positive
50777  Bad plot, bad dialogue, bad acting, idiotic di...  negative
50778  I am a Catholic taught in parochial elementary...  negative
50779  I'm going to have to disagree with the previou...  negative
50780  No one expects the Star Trek movies to be high...  negative

[50781 rows x 2 columns]

#encoding

In [15]:
df['sentiment'].unique()

array(['positive', 'negative'], dtype=object)

In [16]:
df['Sentiment']=df['sentiment'].map({'positive':1,'negative':0})

In [17]:
df.drop(columns='sentiment',inplace=True)

#basic data processing

In [18]:
import re
import string

In [19]:
def clean_text (text):
  text= text.lower()
  # remove html tags
  text = re.sub(r'<.*?>',"",text)
  # remove urls
  text = re.sub(r'http\S+|www\S+','',text)
  # remove emojis
  text = re.sub(r'[^x00-\x7F]+',' ',text)
  # special characters
  text = re.sub(r'[^a-z0-9\s]','',text)
  # white space
  text = re.sub(r'\s+',' ',text).strip()

  return text

In [20]:
df['cleaned_text']=df['review'].apply(clean_text)

In [21]:
df

,review,Sentiment,cleaned_text
0,One of the other reviewers has mentioned that ...,1,one of the other reviewers has mentioned that ...
1,A wonderful little production. <br /><br />The...,1,a wonderful little production the filming tech...
2,I thought this was a wonderful way to spend ti...,1,i thought this was a wonderful way to spend ti...
3,Basically there's a family where a little boy ...,0,basically there s a family where a little boy ...
4,"Petter Mattei's ""Love in the Time of Money"" is...",1,petter mattei s love in the time of money is a...
...,...,...,...
50776,I thought this movie did a down right good job...,1,i thought this movie did a down right good job...
50777,"Bad plot, bad dialogue, bad acting, idiotic di...",0,bad plot bad dialogue bad acting idiotic direc...
50778,I am a Catholic taught in parochial elementary...,0,i am a catholic taught in parochial elementary...
50779,I'm going to have to disagree with the previou...,0,i m going to have to disagree with the previou...
50780,No one expects the Star Trek movies to be high...,0,no one expects the star trek movies to be high...

In [22]:
df.drop(columns='review',inplace=True)

In [23]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50781 entries, 0 to 50780
Data columns (total 2 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Sentiment     50781 non-null  int64
 1   cleaned_text  50781 non-null  object
dtypes: int64(1), object(1)
memory usage: 793.6+ KB

In [24]:
df.isnull().sum()

Sentiment       0
cleaned_text    0
dtype: int64

In [25]:
len(df)

50781

In [26]:
df.loc[4500,'cleaned_text']

'lin mcadam james stewart wins a rifle a winchester in a shooting contest dutch henry brown stephen mcnally is a bad loser and steals the gun lin takes his horse and goes after dutch and his men and the rifle with his buddy high spade millard mitchell the rifle gets in different hands on the way will it get back to the right owner anthony mann and james stewart worked together for the first time and came up with this masterpiece winchester 73 1950 stewart is the right man to play the lead he was always the right man to do anything the terrific shelley winters plays the part of lola manners and she s great as always dan duryea is terrific at the part of waco johnnie dean charles drake is brilliant as lola s cowardly boyfriend steve miller also wyatt earp and bat masterson are seen in the movie and they re played by will geer and steve darrell the young rock hudson plays young bull and the young anthony tony curtis plays doan there are many classic moments in this movie in one point the group is surrounded by indians since this is a western it s great to watch this survival game where the fastest drawer and the sharpest shooter is the winner all the true western fans will love this movie'

#tokennizer

In [27]:
from tensorflow.keras.preprocessing.text import Tokenizer
tokenizer =Tokenizer()
tokenizer.fit_on_texts(df['cleaned_text'])
x=tokenizer.texts_to_sequences(df['cleaned_text'])

In [28]:
x[0]

[28,
 4,
 1,
 77,
 2070,
 46,
 1057,
 11,
 100,
 148,
 41,
 319,
 3085,
 400,
 20,
 231,
 29,
 3239,
 32,
 25,
 204,
 14,
 10,
 6,
 618,
 47,
 596,
 17,
 68,
 1,
 87,
 149,
 11,
 3250,
 68,
 44,
 3085,
 13,
 90,
 5387,
 2,
 15167,
 134,
 4,
 568,
 61,
 266,
 8,
 204,
 37,
 1,
 651,
 141,
 1740,
 68,
 10,
 6,
 23,
 3,
 116,
 16,
 1,
 7889,
 2333,
 40,
 11274,
 10,
 116,
 2618,
 56,
 5966,
 17,
 5523,
 5,
 1463,
 376,
 40,
 568,
 90,
 6,
 3851,
 8,
 1,
 355,
 358,
 4,
 1,
 651,
 7,
 6,
 434,
 3085,
 14,
 11,
 6,
 1,
 11745,
 361,
 5,
 1,
 14620,
 6919,
 2564,
 1040,
 44589,
 7,
 2664,
 1421,
 22,
 23140,
 524,
 34,
 4674,
 2447,
 4,
 1,
 1191,
 115,
 30,
 1,
 7069,
 27,
 2928,
 11905,
 2,
 389,
 51319,
 36,
 16711,
 6,
 23,
 300,
 22,
 1,
 4906,
 2935,
 524,
 6,
 345,
 5,
 107,
 22336,
 7938,
 40072,
 14621,
 5113,
 7771,
 2416,
 2,
 52,
 36,
 44590,
 327,
 8950,
 7368,
 12594,
 2,
 8799,
 31862,
 25,
 111,
 224,
 242,
 9,
 60,
 132,
 1,
 282,
 1326,
 4,
 1,
 116,
 6,
 680,
 5,
 1,
 195,
 11,
 7,
 272,
 115,
 77,
 277,
 581,
 21,
 3046,
 827,
 184,
 1307,
 4132,
 16,
 2492,
 1235,
 827,
 1431,
 827,
 872,
 3085,
 152,
 21,
 949,
 185,
 1,
 87,
 400,
 9,
 123,
 210,
 3250,
 68,
 14,
 36,
 1616,
 7,
 13,
 2232,
 9,
 415,
 21,
 132,
 9,
 13,
 1580,
 16,
 7,
 18,
 14,
 9,
 293,
 52,
 9,
 1422,
 3,
 1268,
 16,
 3085,
 2,
 192,
 10170,
 5,
 1,
 300,
 2046,
 4,
 2138,
 568,
 23,
 41,
 568,
 18,
 7714,
 7223,
 5046,
 35,
 231,
 29,
 2961,
 43,
 16,
 3,
 23141,
 6920,
 35,
 231,
 498,
 22,
 632,
 2,
 75,
 242,
 17,
 7,
 69,
 7529,
 644,
 703,
 6920,
 109,
 655,
 83,
 1191,
 19239,
 680,
 5,
 66,
 567,
 4,
 902,
 2022,
 40,
 1191,
 554,
 148,
 3085,
 20,
 198,
 425,
 3887,
 17,
 47,
 6,
 3328,
 806,
 1513,
 45,
 20,
 50,
 75,
 8,
 1217,
 17,
 126,
 4041,
 485]

In [29]:
y=df['Sentiment']

In [30]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=42)

#padding
it is used to make length of sentences same

In [31]:
from tensorflow.keras.preprocessing.sequence import pad_sequences
x_train=pad_sequences(x_train,maxlen=100,padding='post',truncating='post')
x_test=pad_sequences(x_test,maxlen=100,padding='post',truncating='post')

#RNN

In [32]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding,SimpleRNN,Dense
model=Sequential()
model.add(Embedding(input_dim=5000,output_dim=128))
model.build(input_shape=(None,100))
model.add(SimpleRNN(64))
model.add(Dense(1,activation='sigmoid'))
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ (None, 100, 128)       │       640,000 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ simple_rnn (SimpleRNN)          │ (None, 64)             │        12,352 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense (Dense)                   │ (None, 1)              │            65 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 652,417 (2.49 MB)

 Trainable params: 652,417 (2.49 MB)

 Non-trainable params: 0 (0.00 B)

In [34]:
model.compile(loss='binary_crossentropy',optimizer='Adam',metrics=['accuracy'])

In [35]:
model.fit(x_train,y_train,epochs=20,batch_size=64,verbose=1)

Epoch 1/20
635/635 ━━━━━━━━━━━━━━━━━━━━ 10s 11ms/step - accuracy: 0.5701 - loss: 0.6787
Epoch 2/20
635/635 ━━━━━━━━━━━━━━━━━━━━ 6s 9ms/step - accuracy: 0.5976 - loss: 0.6655
Epoch 3/20
635/635 ━━━━━━━━━━━━━━━━━━━━ 6s 9ms/step - accuracy: 0.6633 - loss: 0.6066
Epoch 4/20
635/635 ━━━━━━━━━━━━━━━━━━━━ 6s 9ms/step - accuracy: 0.7610 - loss: 0.5014
Epoch 5/20
635/635 ━━━━━━━━━━━━━━━━━━━━ 6s 9ms/step - accuracy: 0.7144 - loss: 0.5398
Epoch 6/20
635/635 ━━━━━━━━━━━━━━━━━━━━ 6s 9ms/step - accuracy: 0.7422 - loss: 0.5056
Epoch 7/20
635/635 ━━━━━━━━━━━━━━━━━━━━ 6s 9ms/step - accuracy: 0.7681 - loss: 0.4713
Epoch 8/20
635/635 ━━━━━━━━━━━━━━━━━━━━ 6s 9ms/step - accuracy: 0.8195 - loss: 0.3847
Epoch 9/20
635/635 ━━━━━━━━━━━━━━━━━━━━ 6s 9ms/step - accuracy: 0.8494 - loss: 0.3258
Epoch 10/20
635/635 ━━━━━━━━━━━━━━━━━━━━ 6s 9ms/step - accuracy: 0.8642 - loss: 0.2999
Epoch 11/20
635/635 ━━━━━━━━━━━━━━━━━━━━ 6s 9ms/step - accuracy: 0.8533 - loss: 0.3168
Epoch 12/20
635/635 ━━━━━━━━━━━━━━━━━━━━ 6s 9ms/step - accuracy: 0.8800 - loss: 0.2690
Epoch 13/20
635/635 ━━━━━━━━━━━━━━━━━━━━ 6s 9ms/step - accuracy: 0.8593 - loss: 0.3078
Epoch 14/20
635/635 ━━━━━━━━━━━━━━━━━━━━ 6s 9ms/step - accuracy: 0.8944 - loss: 0.2376
Epoch 15/20
635/635 ━━━━━━━━━━━━━━━━━━━━ 6s 9ms/step - accuracy: 0.9161 - loss: 0.1910
Epoch 16/20
635/635 ━━━━━━━━━━━━━━━━━━━━ 6s 9ms/step - accuracy: 0.9428 - loss: 0.1557
Epoch 17/20
635/635 ━━━━━━━━━━━━━━━━━━━━ 6s 9ms/step - accuracy: 0.9266 - loss: 0.1802
Epoch 18/20
635/635 ━━━━━━━━━━━━━━━━━━━━ 6s 9ms/step - accuracy: 0.9370 - loss: 0.1659
Epoch 19/20
635/635 ━━━━━━━━━━━━━━━━━━━━ 6s 9ms/step - accuracy: 0.8627 - loss: 0.3045
Epoch 20/20
635/635 ━━━━━━━━━━━━━━━━━━━━ 6s 9ms/step - accuracy: 0.9118 - loss: 0.1949

In [38]:
loss,accuracy=model.evaluate(x_test,y_test)

318/318 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.5652 - loss: 1.6168

In [39]:
from tensorflow.keras.layers import LSTM

In [42]:
model=Sequential()
model.add(Embedding(input_dim=5000,output_dim=128))
model.build(input_shape=(None,100))
model.add(LSTM(64))
model.add(Dense(1,activation='sigmoid'))
model.summary()

Model: "sequential_2"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_2 (Embedding)         │ (None, 100, 128)       │       640,000 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm (LSTM)                     │ (None, 64)             │        49,408 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 1)              │            65 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 689,473 (2.63 MB)

 Trainable params: 689,473 (2.63 MB)

 Non-trainable params: 0 (0.00 B)

In [43]:
model.compile(loss='binary_crossentropy',optimizer='Adam',metrics=['accuracy'])

In [44]:
model.fit(x_train,y_train,epochs=50,batch_size=64,verbose=1)

Epoch 1/50
635/635 ━━━━━━━━━━━━━━━━━━━━ 8s 8ms/step - accuracy: 0.7493 - loss: 0.5168
Epoch 2/50
635/635 ━━━━━━━━━━━━━━━━━━━━ 6s 9ms/step - accuracy: 0.8184 - loss: 0.4114
Epoch 3/50
635/635 ━━━━━━━━━━━━━━━━━━━━ 5s 8ms/step - accuracy: 0.8573 - loss: 0.3405
Epoch 4/50
635/635 ━━━━━━━━━━━━━━━━━━━━ 6s 9ms/step - accuracy: 0.8741 - loss: 0.3046
Epoch 5/50
635/635 ━━━━━━━━━━━━━━━━━━━━ 6s 9ms/step - accuracy: 0.8912 - loss: 0.2666
Epoch 6/50
635/635 ━━━━━━━━━━━━━━━━━━━━ 6s 9ms/step - accuracy: 0.9060 - loss: 0.2399
Epoch 7/50
635/635 ━━━━━━━━━━━━━━━━━━━━ 10s 8ms/step - accuracy: 0.9203 - loss: 0.2104
Epoch 8/50
635/635 ━━━━━━━━━━━━━━━━━━━━ 6s 9ms/step - accuracy: 0.9321 - loss: 0.1841
Epoch 9/50
635/635 ━━━━━━━━━━━━━━━━━━━━ 5s 8ms/step - accuracy: 0.9433 - loss: 0.1584
Epoch 10/50
635/635 ━━━━━━━━━━━━━━━━━━━━ 6s 10ms/step - accuracy: 0.9517 - loss: 0.1400
Epoch 11/50
635/635 ━━━━━━━━━━━━━━━━━━━━ 5s 8ms/step - accuracy: 0.9582 - loss: 0.1231
Epoch 12/50
635/635 ━━━━━━━━━━━━━━━━━━━━ 8s 13ms/step - accuracy: 0.9624 - loss: 0.1137
Epoch 13/50
635/635 ━━━━━━━━━━━━━━━━━━━━ 6s 9ms/step - accuracy: 0.9732 - loss: 0.0863
Epoch 14/50
635/635 ━━━━━━━━━━━━━━━━━━━━ 6s 9ms/step - accuracy: 0.9537 - loss: 0.1334
Epoch 15/50
635/635 ━━━━━━━━━━━━━━━━━━━━ 5s 9ms/step - accuracy: 0.9743 - loss: 0.0822
Epoch 16/50
635/635 ━━━━━━━━━━━━━━━━━━━━ 7s 11ms/step - accuracy: 0.9833 - loss: 0.0581
Epoch 17/50
635/635 ━━━━━━━━━━━━━━━━━━━━ 5s 8ms/step - accuracy: 0.9838 - loss: 0.0557
Epoch 18/50
635/635 ━━━━━━━━━━━━━━━━━━━━ 5s 8ms/step - accuracy: 0.9859 - loss: 0.0498
Epoch 19/50
635/635 ━━━━━━━━━━━━━━━━━━━━ 6s 10ms/step - accuracy: 0.9868 - loss: 0.0458
Epoch 20/50
635/635 ━━━━━━━━━━━━━━━━━━━━ 6s 9ms/step - accuracy: 0.9876 - loss: 0.0426
Epoch 21/50
635/635 ━━━━━━━━━━━━━━━━━━━━ 11s 10ms/step - accuracy: 0.9895 - loss: 0.0352
Epoch 22/50
635/635 ━━━━━━━━━━━━━━━━━━━━ 7s 11ms/step - accuracy: 0.9920 - loss: 0.0293
Epoch 23/50
635/635 ━━━━━━━━━━━━━━━━━━━━ 5s 8ms/step - accuracy: 0.9888 - loss: 0.0395
Epoch 24/50
635/635 ━━━━━━━━━━━━━━━━━━━━ 6s 9ms/step - accuracy: 0.9935 - loss: 0.0259
Epoch 25/50
635/635 ━━━━━━━━━━━━━━━━━━━━ 5s 8ms/step - accuracy: 0.9960 - loss: 0.0171
Epoch 26/50
635/635 ━━━━━━━━━━━━━━━━━━━━ 6s 9ms/step - accuracy: 0.9924 - loss: 0.0263
Epoch 27/50
635/635 ━━━━━━━━━━━━━━━━━━━━ 5s 8ms/step - accuracy: 0.9914 - loss: 0.0309
Epoch 28/50
635/635 ━━━━━━━━━━━━━━━━━━━━ 5s 9ms/step - accuracy: 0.9928 - loss: 0.0279
Epoch 29/50
635/635 ━━━━━━━━━━━━━━━━━━━━ 10s 9ms/step - accuracy: 0.9964 - loss: 0.0159
Epoch 30/50
635/635 ━━━━━━━━━━━━━━━━━━━━ 6s 10ms/step - accuracy: 0.9949 - loss: 0.0201
Epoch 31/50
635/635 ━━━━━━━━━━━━━━━━━━━━ 10s 10ms/step - accuracy: 0.9973 - loss: 0.0120
Epoch 32/50
635/635 ━━━━━━━━━━━━━━━━━━━━ 9s 8ms/step - accuracy: 0.9934 - loss: 0.0243
Epoch 33/50
635/635 ━━━━━━━━━━━━━━━━━━━━ 6s 9ms/step - accuracy: 0.9941 - loss: 0.0212
Epoch 34/50
635/635 ━━━━━━━━━━━━━━━━━━━━ 5s 8ms/step - accuracy: 0.9955 - loss: 0.0168
Epoch 35/50
635/635 ━━━━━━━━━━━━━━━━━━━━ 6s 9ms/step - accuracy: 0.9980 - loss: 0.0084
Epoch 36/50
635/635 ━━━━━━━━━━━━━━━━━━━━ 10s 8ms/step - accuracy: 0.9970 - loss: 0.0114
Epoch 37/50
635/635 ━━━━━━━━━━━━━━━━━━━━ 6s 9ms/step - accuracy: 0.9953 - loss: 0.0181
Epoch 38/50
635/635 ━━━━━━━━━━━━━━━━━━━━ 5s 8ms/step - accuracy: 0.9969 - loss: 0.0135
Epoch 39/50
635/635 ━━━━━━━━━━━━━━━━━━━━ 6s 9ms/step - accuracy: 0.9955 - loss: 0.0161
Epoch 40/50
635/635 ━━━━━━━━━━━━━━━━━━━━ 5s 8ms/step - accuracy: 0.9970 - loss: 0.0114
Epoch 41/50
635/635 ━━━━━━━━━━━━━━━━━━━━ 8s 12ms/step - accuracy: 0.9982 - loss: 0.0079
Epoch 42/50
635/635 ━━━━━━━━━━━━━━━━━━━━ 5s 8ms/step - accuracy: 0.9986 - loss: 0.0062
Epoch 43/50
635/635 ━━━━━━━━━━━━━━━━━━━━ 5s 8ms/step - accuracy: 0.9976 - loss: 0.0084
Epoch 44/50
635/635 ━━━━━━━━━━━━━━━━━━━━ 6s 9ms/step - accuracy: 0.9974 - loss: 0.0099
Epoch 45/50
635/635 ━━━━━━━━━━━━━━━━━━━━ 5s 8ms/step - accuracy: 0.9978 - loss: 0.0090
Epoch 46/50
635/635 ━━━━━━━━━━━━━━━━━━━━ 6s 9ms/step - accuracy: 0.9950 - loss: 0.0185
Epoch 47/50
635/635 ━━━━━━━━━━━━━━━━━━━━ 5s 8ms/step - accuracy: 0.9985 - loss: 0.0067
Epoch 48/50
635/635 ━━━━━━━━━━━━━━━━━━━━ 5s 9ms/step - accuracy: 0.9967 - loss: 0.0131
Epoch 49/50
635/635 ━━━━━━━━━━━━━━━━━━━━ 5s 8ms/step - accuracy: 0.9987 - loss: 0.0056
Epoch 50/50
635/635 ━━━━━━━━━━━━━━━━━━━━ 5s 8ms/step - accuracy: 0.9992 - loss: 0.0038

In [45]:
loss,accuracy=model.evaluate(x_test,y_test)

318/318 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - accuracy: 0.8124 - loss: 1.2370

In [46]:
from tensorflow.keras.layers import GRU

In [47]:
model=Sequential()
model.add(Embedding(input_dim=5000,output_dim=128))
model.build(input_shape=(None,100))
model.add(GRU(64))
model.add(Dense(1,activation='sigmoid'))
model.summary()

Model: "sequential_3"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_3 (Embedding)         │ (None, 100, 128)       │       640,000 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ gru (GRU)                       │ (None, 64)             │        37,248 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_3 (Dense)                 │ (None, 1)              │            65 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 677,313 (2.58 MB)

 Trainable params: 677,313 (2.58 MB)

 Non-trainable params: 0 (0.00 B)

In [48]:
model.compile(loss='binary_crossentropy',optimizer='Adam',metrics=['accuracy'])

In [49]:
model.fit(x_train,y_train,epochs=50,batch_size=64,verbose=1)

Epoch 1/50
635/635 ━━━━━━━━━━━━━━━━━━━━ 7s 9ms/step - accuracy: 0.7536 - loss: 0.4908
Epoch 2/50
635/635 ━━━━━━━━━━━━━━━━━━━━ 5s 8ms/step - accuracy: 0.8587 - loss: 0.3337
Epoch 3/50
635/635 ━━━━━━━━━━━━━━━━━━━━ 6s 9ms/step - accuracy: 0.8827 - loss: 0.2836
Epoch 4/50
635/635 ━━━━━━━━━━━━━━━━━━━━ 10s 8ms/step - accuracy: 0.9009 - loss: 0.2417
Epoch 5/50
635/635 ━━━━━━━━━━━━━━━━━━━━ 5s 8ms/step - accuracy: 0.9184 - loss: 0.2042
Epoch 6/50
635/635 ━━━━━━━━━━━━━━━━━━━━ 5s 7ms/step - accuracy: 0.9374 - loss: 0.1650
Epoch 7/50
635/635 ━━━━━━━━━━━━━━━━━━━━ 6s 9ms/step - accuracy: 0.9519 - loss: 0.1309
Epoch 8/50
635/635 ━━━━━━━━━━━━━━━━━━━━ 5s 8ms/step - accuracy: 0.9627 - loss: 0.1005
Epoch 9/50
635/635 ━━━━━━━━━━━━━━━━━━━━ 5s 8ms/step - accuracy: 0.9729 - loss: 0.0775
Epoch 10/50
635/635 ━━━━━━━━━━━━━━━━━━━━ 5s 8ms/step - accuracy: 0.9798 - loss: 0.0584
Epoch 11/50
635/635 ━━━━━━━━━━━━━━━━━━━━ 5s 7ms/step - accuracy: 0.9820 - loss: 0.0546
Epoch 12/50
635/635 ━━━━━━━━━━━━━━━━━━━━ 6s 9ms/step - accuracy: 0.9893 - loss: 0.0353
Epoch 13/50
635/635 ━━━━━━━━━━━━━━━━━━━━ 5s 8ms/step - accuracy: 0.9904 - loss: 0.0305
Epoch 14/50
635/635 ━━━━━━━━━━━━━━━━━━━━ 5s 9ms/step - accuracy: 0.9933 - loss: 0.0218
Epoch 15/50
635/635 ━━━━━━━━━━━━━━━━━━━━ 5s 8ms/step - accuracy: 0.9933 - loss: 0.0205
Epoch 16/50
635/635 ━━━━━━━━━━━━━━━━━━━━ 5s 7ms/step - accuracy: 0.9941 - loss: 0.0192
Epoch 17/50
635/635 ━━━━━━━━━━━━━━━━━━━━ 6s 9ms/step - accuracy: 0.9950 - loss: 0.0166
Epoch 18/50
635/635 ━━━━━━━━━━━━━━━━━━━━ 5s 8ms/step - accuracy: 0.9953 - loss: 0.0139
Epoch 19/50
635/635 ━━━━━━━━━━━━━━━━━━━━ 6s 9ms/step - accuracy: 0.9959 - loss: 0.0121
Epoch 20/50
635/635 ━━━━━━━━━━━━━━━━━━━━ 5s 8ms/step - accuracy: 0.9953 - loss: 0.0160
Epoch 21/50
635/635 ━━━━━━━━━━━━━━━━━━━━ 5s 7ms/step - accuracy: 0.9960 - loss: 0.0119
Epoch 22/50
635/635 ━━━━━━━━━━━━━━━━━━━━ 6s 9ms/step - accuracy: 0.9979 - loss: 0.0082
Epoch 23/50
635/635 ━━━━━━━━━━━━━━━━━━━━ 5s 7ms/step - accuracy: 0.9986 - loss: 0.0049
Epoch 24/50
635/635 ━━━━━━━━━━━━━━━━━━━━ 6s 9ms/step - accuracy: 0.9976 - loss: 0.0078
Epoch 25/50
635/635 ━━━━━━━━━━━━━━━━━━━━ 10s 8ms/step - accuracy: 0.9938 - loss: 0.0185
Epoch 26/50
635/635 ━━━━━━━━━━━━━━━━━━━━ 6s 9ms/step - accuracy: 0.9972 - loss: 0.0090
Epoch 27/50
635/635 ━━━━━━━━━━━━━━━━━━━━ 10s 9ms/step - accuracy: 0.9979 - loss: 0.0069
Epoch 28/50
635/635 ━━━━━━━━━━━━━━━━━━━━ 5s 7ms/step - accuracy: 0.9976 - loss: 0.0074
Epoch 29/50
635/635 ━━━━━━━━━━━━━━━━━━━━ 5s 8ms/step - accuracy: 0.9987 - loss: 0.0047
Epoch 30/50
635/635 ━━━━━━━━━━━━━━━━━━━━ 5s 8ms/step - accuracy: 0.9977 - loss: 0.0074
Epoch 31/50
635/635 ━━━━━━━━━━━━━━━━━━━━ 5s 8ms/step - accuracy: 0.9967 - loss: 0.0107
Epoch 32/50
635/635 ━━━━━━━━━━━━━━━━━━━━ 6s 9ms/step - accuracy: 0.9975 - loss: 0.0075
Epoch 33/50
635/635 ━━━━━━━━━━━━━━━━━━━━ 5s 8ms/step - accuracy: 0.9982 - loss: 0.0058
Epoch 34/50
635/635 ━━━━━━━━━━━━━━━━━━━━ 6s 9ms/step - accuracy: 0.9976 - loss: 0.0076
Epoch 35/50
635/635 ━━━━━━━━━━━━━━━━━━━━ 5s 8ms/step - accuracy: 0.9987 - loss: 0.0048
Epoch 36/50
635/635 ━━━━━━━━━━━━━━━━━━━━ 5s 8ms/step - accuracy: 0.9992 - loss: 0.0027
Epoch 37/50
635/635 ━━━━━━━━━━━━━━━━━━━━ 6s 9ms/step - accuracy: 0.9978 - loss: 0.0071
Epoch 38/50
635/635 ━━━━━━━━━━━━━━━━━━━━ 10s 9ms/step - accuracy: 0.9982 - loss: 0.0058
Epoch 39/50
635/635 ━━━━━━━━━━━━━━━━━━━━ 5s 8ms/step - accuracy: 0.9989 - loss: 0.0036
Epoch 40/50
635/635 ━━━━━━━━━━━━━━━━━━━━ 5s 8ms/step - accuracy: 0.9983 - loss: 0.0057
Epoch 41/50
635/635 ━━━━━━━━━━━━━━━━━━━━ 6s 9ms/step - accuracy: 0.9987 - loss: 0.0048
Epoch 42/50
635/635 ━━━━━━━━━━━━━━━━━━━━ 5s 8ms/step - accuracy: 0.9987 - loss: 0.0036
Epoch 43/50
635/635 ━━━━━━━━━━━━━━━━━━━━ 6s 9ms/step - accuracy: 0.9987 - loss: 0.0041
Epoch 44/50
635/635 ━━━━━━━━━━━━━━━━━━━━ 10s 9ms/step - accuracy: 0.9991 - loss: 0.0031
Epoch 45/50
635/635 ━━━━━━━━━━━━━━━━━━━━ 5s 8ms/step - accuracy: 0.9982 - loss: 0.0060
Epoch 46/50
635/635 ━━━━━━━━━━━━━━━━━━━━ 6s 9ms/step - accuracy: 0.9993 - loss: 0.0027
Epoch 47/50
635/635 ━━━━━━━━━━━━━━━━━━━━ 7s 10ms/step - accuracy: 0.9984 - loss: 0.0063
Epoch 48/50
635/635 ━━━━━━━━━━━━━━━━━━━━ 5s 8ms/step - accuracy: 0.9984 - loss: 0.0043
Epoch 49/50
635/635 ━━━━━━━━━━━━━━━━━━━━ 6s 9ms/step - accuracy: 0.9990 - loss: 0.0031
Epoch 50/50
635/635 ━━━━━━━━━━━━━━━━━━━━ 5s 8ms/step - accuracy: 0.9994 - loss: 0.0025

In [50]:
loss,accuracy=model.evaluate(x_test,y_test)

318/318 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - accuracy: 0.8174 - loss: 1.6995