In [1]:
import numpy as np
import pandas as pd

In [2]:
df=pd.read_csv("/content/IMDB Dataset.csv")

In [3]:
df

                                                  review sentiment
0      One of the other reviewers has mentioned that ...  positive
1      A wonderful little production. <br /><br />The...  positive
2      I thought this was a wonderful way to spend ti...  positive
3      Basically there's a family where a little boy ...  negative
4      Petter Mattei's "Love in the Time of Money" is...  positive
...                                                  ...       ...
49995  I thought this movie did a down right good job...  positive
49996  Bad plot, bad dialogue, bad acting, idiotic di...  negative
49997  I am a Catholic taught in parochial elementary...  negative
49998  I'm going to have to disagree with the previou...  negative
49999  No one expects the Star Trek movies to be high...  negative

[50000 rows x 2 columns]

#encoding

In [4]:
df['sentiment'].unique()

array(['positive', 'negative'], dtype=object)

In [5]:
df['Sentiment']=df['sentiment'].map({'positive':1,'negative':0})

In [6]:
df.drop(columns='sentiment',inplace=True)

#basic data processing

In [7]:
import re
import string

In [8]:
def clean_text (text):
  text= text.lower()
  # remove html tags
  text = re.sub(r'<.*?>',"",text)
  # remove urls
  text = re.sub(r'http\S+|www\S+','',text)
  # remove emojis
  text = re.sub(r'[^x00-\x7F]+',' ',text)
  # special characters
  text = re.sub(r'[^a-z0-9\s]','',text)
  # white space
  text = re.sub(r'\s+',' ',text).strip()

  return text

In [9]:
df['cleaned_text']=df['review'].apply(clean_text)

In [10]:
df

,review,Sentiment,cleaned_text
0,One of the other reviewers has mentioned that ...,1,one of the other reviewers has mentioned that ...
1,A wonderful little production. <br /><br />The...,1,a wonderful little production the filming tech...
2,I thought this was a wonderful way to spend ti...,1,i thought this was a wonderful way to spend ti...
3,Basically there's a family where a little boy ...,0,basically there s a family where a little boy ...
4,"Petter Mattei's ""Love in the Time of Money"" is...",1,petter mattei s love in the time of money is a...
...,...,...,...
49995,I thought this movie did a down right good job...,1,i thought this movie did a down right good job...
49996,"Bad plot, bad dialogue, bad acting, idiotic di...",0,bad plot bad dialogue bad acting idiotic direc...
49997,I am a Catholic taught in parochial elementary...,0,i am a catholic taught in parochial elementary...
49998,I'm going to have to disagree with the previou...,0,i m going to have to disagree with the previou...
49999,No one expects the Star Trek movies to be high...,0,no one expects the star trek movies to be high...

In [11]:
df.drop(columns='review',inplace=True)

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 2 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Sentiment     50000 non-null  int64
 1   cleaned_text  50000 non-null  object
dtypes: int64(1), object(1)
memory usage: 781.4+ KB

In [13]:
df.isnull().sum()

Sentiment       0
cleaned_text    0
dtype: int64

In [14]:
len(df)

50000